apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/application

patches:
- target:
    kind: Application
    name: helm-guestbook
  patch: |-
    - op: replace
      path: /spec/source/helm/valueFiles
      value: ["values-production.yaml"]