apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/application

patches:
- target:
    kind: Application
    name: sealed-secrets
  patch: |-
    - op: replace
      path: /spec/source/helm/valuesFile
      value: ["values-production.yaml"]