apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
  - repoURL: https://github.com/amar-chand/argocd-public.git
    targetRevision: HEAD
    path: examples/kustomize-to-modify-argo-manifests/overlays/prod/application/
  destination:
    name: in-cluster
    namespace: default
