apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amar-chand/argocd-public.git
    targetRevision: HEAD
    path: examples/kustomize-to-modify-argo-manifests/overlays/prod/application-with-values-in-different-repo/
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
    - CreateNamespace=true