apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/application-with-values-in-different-repo

patches:
- target:
    kind: Application
    name: nginx-app
  patch: |-
    - op: replace
      path: /spec/sources/0/helm/valueFiles
      value: ["$values/examples/kustomize-to-modify-argo-manifests/base/application-with-values-in-different-repo/resources/old-values.yaml"]